version: '3'
services:
  api:
    build:
      context: ./random-number-api
    ports:
      - "3000:3000"

  client:
    build:
      context: ./random-number-client
    ports:
      - "80:80"
    depends_on:
      - api
